// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    $('.name').editable(function(value, settings) {
      return value;
    });
    return $('.attribute').editable(function(value, settings) {
      $(this).attr('data-attribute', value);
      return "";
    }, {
      placeholder: "",
      data: JSON.stringify({
        'water': '水',
        'fire': '炎'
      }),
      type: 'select',
      submit: 'OK'
    });
  });

}).call(this);
