// Generated by CoffeeScript 1.6.1
(function() {

  $(document).ready(function() {
    $('#card_form').submit(function() {
      return this.document.value = $('.card')[0].outerHTML;
    });
    $('.name').editable(function(value, settings) {
      return value;
    });
    $('.attribute').editable(function(value, settings) {
      return $(this).attr('data-attribute', value);
    }, {
      placeholder: "",
      data: JSON.stringify({
        'water': '水',
        'fire': '炎'
      }),
      type: 'select',
      submit: 'OK'
    });
    $('.monster_type').editable(function(value, settings) {
      return value;
    });
    $('.number').editable(function(value, settings) {
      return value;
    });
    $('.edition').editable(function(value, settings) {
      return value;
    });
    $('.rule_text').editable(function(value, settings) {
      return value;
    }, {
      type: 'textarea',
      submit: 'OK'
    });
    $('.name').editable(function(value, settings) {
      return value;
    });
    $('.gamecode').editable(function(value, settings) {
      return value;
    });
    $('.atk').editable(function(value, settings) {
      return value;
    });
    return $('.def').editable(function(value, settings) {
      return value;
    });
  });

}).call(this);
